name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rspec:
    name: "Run tests"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.1
          - ruby: 3.0
          - ruby: 2.7
          - ruby: 2.6
          - ruby: 2.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /home/runner/bundle
          key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
            bundle-${{ matrix.ruby }}-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          bundle config path /home/runner/bundle
          bundle install
          bundle update
      - name: Run RSpec
        run: |
          bundle exec rspec
